version: "3"

services:

  auth:
    image: why-auth:1.0-SNAPSHOT
    ports:
      - 9000:9000
    hostname: auth
    environment:
      CASSANDRA_HOST: "vps191847.ovh.net"
      CASS_USER: "why"
      CASS_PASS: "cassandraIbpltgmsw2"
      ELASTIC_HOST: "vps324214.ovh.net"
      ELASTIC_PASS: "elasticIbpltgmsw2"
      SEED_HOST: auth
      CLUSTER_IP: auth
    networks:
      - pieczkinetwork
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M

  blog:
    image: why-blog:1.0-SNAPSHOT
    ports:
      - 9001:9000
    hostname: blog
    depends_on:
      - auth
    environment:
      CASSANDRA_HOST: "vps191847.ovh.net"
      CASS_USER: "why"
      CASS_PASS: "cassandraIbpltgmsw2"
      ELASTIC_HOST: "vps324214.ovh.net"
      ELASTIC_PASS: "elasticIbpltgmsw2"
      SEED_HOST: blog
      CLUSTER_IP: blog
      AUTH_HOST_PORT: auth:9000
    networks:
      - pieczkinetwork
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M

  comment:
    image: why-comment:1.0-SNAPSHOT
    ports:
      - 9002:9000
    hostname: comment
    depends_on:
      - auth
      - blog
    environment:
      CASSANDRA_HOST: "vps191847.ovh.net"
      CASS_USER: "why"
      CASS_PASS: "cassandraIbpltgmsw2"
      ELASTIC_HOST: "vps324214.ovh.net"
      ELASTIC_PASS: "elasticIbpltgmsw2"
      SEED_HOST: comment
      CLUSTER_IP: comment
      AUTH_HOST_PORT: auth:9000
      POST_HOST_PORT: blog:9000
    networks:
      - pieczkinetwork
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M

  front:
    image: blog-front:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - blog
      - comment
    networks:
      - pieczkinetwork
    volumes:
      - /home/why/pieczki/assets/img/:/usr/share/nginx/html/prod/assets/img/
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.3'
          memory: 256M


networks:
  pieczkinetwork:


